url: "https://oleg-nenashev.github.io/"
baseurl: "wiremock.org/"

# Analytics
analytics:
  google:
      # gtag
      id: "G-F923LHBYYT"

  # MS Clarity
  clarity:
      enabled: true
  vwo:
      enabled: true

# TODO: Update plugin code to support more fancy navigation
breadcrumbs:
  root:
    hide: true
    image: true
    imagePath: /wiremock.org/images/logos/doc-sections/home.svg
