site_name: WireMock Documentation
site_description: >-
  WireMock Documentation.
copyright: Copyright &copy; 2023 - WireMock Contributors
docs_dir: _docs

# Build
site_dir: _site-docs


theme:
  name: material
  highlightjs: true
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    # NOT compatible qith toc.integrate
    # - navigation.indexes
    - navigation.path
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.expand
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  font:
    text: DM Sans
    code: Roboto Mono
  favicon: assets/images/favicon.svg
  logo: images/logos/wiremock/logo_wide.svg

extra:
  social:
    - icon: fontawesome/brands/slack
      link: https://slack.wiremock.org/
      name: WireMock Community Slack
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/wiremockorg
      name: WireMock on Twitter
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/wiremock/
      name: WireMock on LinkedIn
    - icon: fontawesome/brands/mastodon
      link: https://fosstodon.org/@wiremock
      name: WireMock on Fosstodon
  
    
extra_css:
  - assets/css/wiremock.css

plugins:
  - search
  - multirepo:
      # TODO: Change to True once works
      cleanup: false
      keep_docs_dir: true
      nav_repos:
        - name: graphql
          import_url: 'https://github.com/wiremock/wiremock-graphql-extension?branch=main&edit_uri=/blob/main/'
          imports: [ /README.md, docs/* ]
        - name: grpc
          import_url: 'https://github.com/wiremock/wiremock-grpc-extension?branch=main&edit_uri=/blob/main/'
          imports: [ /README.md, docs/* ]
        - name: state
          import_url: 'https://github.com/wiremock/wiremock-extension-state?branch=develop&edit_uri=/blob/develop/'
          imports: [ /README.md, docs/*  ]
 
          
        # Outside WireMock GitHub org
        - name: 9cookies
          import_url: 'https://github.com/9cookies/wiremock-extensions?branch=master&edit_uri=/blob/master/'
          imports: [ /*.md ]
        - name: jwt
          import_url: 'https://github.com/MasonM/wiremock-jwt-extension?branch=master&edit_uri=/blob/master/'
          imports: [ /README.md ]
        - name: cors
          import_url: 'https://github.com/RichieLoco/WiremockCorsExtension?branch=master&edit_uri=/blob/master/'
          imports: [ /README.md ]
        - name: stub-mapping-tracker
          import_url: 'https://github.com/MasonM/wiremock-stub-mapping-tracker?branch=master&edit_uri=/blob/master/'
          imports: [ /README.md ]
        - name: prometheus
          import_url: 'https://github.com/mikeskali/wiremock-metrics?branch=master&edit_uri=/blob/master/'
          imports: [ /README.md ]
        - name: record-delay
          import_url: 'https://github.com/anuragashok/wiremock-extension-record-delay?branch=main&edit_uri=/blob/main/'
          imports: [ /README.md ]
        
        # System
        - name: community
          import_url: 'https://github.com/wiremock/community?branch=main&edit_uri=/blob/main/'
          imports: [ contributing/* ]
        - name: dotgithub
          import_url: 'https://github.com/wiremock/.github?branch=main&edit_uri=/blob/main/'
          imports: [ CONTRIBUTING.md, SECURITY.md, CODE_OF_CONDUCT.md ]
        

nav:
  - Using WireMock:
    - Getting started:
        - Overview: overview.md
        - "Quick Start: API Mocking with Java and JUnit 4": quickstart/java-junit.md
        - Download and Installation: download-and-installation.md
        - WireMock Tutorials: getting-started.md
        - FAQ: faq.md
    - WireMock Standalone:
        - Running in Docker: standalone/docker.md
        - Running as a Standalone Process: standalone/java-jar.md
        - Administration API: standalone/administration.md
    - Java Usage:
        - JUnit 5+ Jupiter: junit-jupiter.md
        - JUnit 4 and Vintage: junit-extensions.md
        - Spring Boot: spring-boot.md
        - Plain Java: java-usage.md
        - Java configuration: configuration.md
        - Running without the HTTP Server: running-without-http-server  .md
    - Stubbing & Verifying:
        - Stubbing: stubbing.md
        - Request Matching: request-matching.md
        - Response Templating: response-templating.md
        - Simulating Faults: simulating-faults.md
        - Stateful Behaviour: stateful-behaviour.md
        - Proxying: proxying.md
        - Verifying: verifying.md
    - Templating:
        - WireMock API Templates Library: mock-api-templates.md
        - Using Mock API Templates: mock-api-templates/usage.md
    - Record & Playback:
        - Record and Playback: record-playback.md
    - Protocols:
        - Webhooks and Callbacks: webhooks-and-callbacks.md
        - Mocking gRPC services: grpc.md
        - WireMock and GraphQL: solutions/graphql.md
        - Serving HTTPs: https.md
    - Advanced use-cases:
        - Multi-domain Mocking: multi-domain-mocking.md
        - Deploying into a servlet container: advanced/deploy-to-servlet-container.md
        - "WireMock on Java 1.7": advanced/java7.md
    - Reference:
        - Admin API: standalone/admin-api-reference.md
        - Security: dotgithub/SECURITY.md
        - WireMock API Templates Library: mock-api-templates.md

  - Extensions:
    - Features:
      - gRPC: grpc/README.md
      - GraphQL: graphql/README.md
      - Response Template Transformer: wiremock/_docs/response-templating.md
      - State: state/README.md
      - Webhooks: wiremock/_docs/webhooks-and-callbacks.md
      - CORS protection: cors/README.md
      - JSON Web Tokens (JWT): jwt/README.md
      - JSON Body Transformer: 9cookies/json-body-transformer.md
      - Request Time Matcher: 9cookies/request-time-matcher.md
    - Operations Extensions:
      - Prometheus Metrics: prometheus/README.md
    - Developer Extensions:
      - Callback Simulator: 9cookies/callback-simulator.md
      - Keywords: 9cookies/keywords.md
      - Stub Mapping Tracker: stub-mapping-tracker/README.md
      - Record Delay Capture: record-delay/README.md

  - Extending WireMock:
    - Extending WireMock: extending-wiremock.md
    - Filtering and Modifying Requests: extensibility/filtering-requests.md
    - Transforming Responses: extensibility/transforming-responses.md
    - Custom Matching: extensibility/custom-matching.md
    - Listening for Serve Events: extensibility/listening-for-serve-events.md
    - Admin API Extensions: extensibility/extending-the-admin-api.md
    - Adding Template Helpers: extensibility/adding-template-helpers.md
    - Adding Template Model Data: extensibility/adding-template-model-data.md
    - Listening for Stub Changes: extensibility/listening-for-stub-changes.md
    - Listening for Settings Changes: extensibility/listening-for-settings-changes.md
    - Mappings Loader Extensions: extensibility/adding-mappings-loader.md
    - Stub Metadata: stub-metadata.md
  
  - Contributing:
    - Contributor Guide: community/contributing/README.md 
    - Hacktoberfest 2023: dotgithub/CONTRIBUTING.md
    - Creating Extensions: wiremock/_docs/extending-wiremock.md
    - Code of Conduct: dotgithub/CODE_OF_CONDUCT.md

 # Markdown
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
