site_name: WireMock Documentation
site_description: >-
  WireMock Documentation.
copyright: Copyright &copy; 2023 - WireMock Contributors
docs_dir: _docs

# Build
site_dir: _site-docs


theme:
  name: material
  highlightjs: true
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    # NOT compatible qith toc.integrate
    # - navigation.indexes
    - navigation.path
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.expand
    #- navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  font:
    text: DM Sans
    code: Roboto Mono
  favicon: images/logos/wiremock/logo_small.svg
  logo: images/logos/wiremock/logo_wide.svg

extra:
  social:
    - icon: fontawesome/brands/slack
      link: https://slack.wiremock.org/
      name: WireMock Community Slack
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/wiremockorg
      name: WireMock on Twitter
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/wiremock/
      name: WireMock on LinkedIn
    - icon: fontawesome/brands/mastodon
      link: https://fosstodon.org/@wiremock
      name: WireMock on Fosstodon
  
    
extra_css:
  - assets/css/wiremock.css

plugins:
  - search
  - multirepo:
      # TODO: Change to True once works
      cleanup: false
      keep_docs_dir: true
      nav_repos:
        - name: graphql
          import_url: 'https://github.com/wiremock/wiremock-graphql-extension?branch=main&edit_uri=/blob/main/'
          imports: [ /README.md, docs/* ]
        - name: grpc
          import_url: 'https://github.com/wiremock/wiremock-grpc-extension?branch=main&edit_uri=/blob/main/'
          imports: [ /README.md, docs/* ]
        - name: state
          import_url: 'https://github.com/wiremock/wiremock-extension-state?branch=develop&edit_uri=/blob/develop/'
          imports: [ /README.md, docs/*  ]
 
          
        # Outside WireMock GitHub org
        - name: 9cookies
          import_url: 'https://github.com/9cookies/wiremock-extensions?branch=master&edit_uri=/blob/master/'
          imports: [ /*.md ]
        - name: jwt
          import_url: 'https://github.com/MasonM/wiremock-jwt-extension?branch=master&edit_uri=/blob/master/'
          imports: [ /README.md ]
        - name: cors
          import_url: 'https://github.com/RichieLoco/WiremockCorsExtension?branch=master&edit_uri=/blob/master/'
          imports: [ /README.md ]
        - name: stub-mapping-tracker
          import_url: 'https://github.com/MasonM/wiremock-stub-mapping-tracker?branch=master&edit_uri=/blob/master/'
          imports: [ /README.md ]
        - name: prometheus
          import_url: 'https://github.com/mikeskali/wiremock-metrics?branch=master&edit_uri=/blob/master/'
          imports: [ /README.md ]
        - name: record-delay
          import_url: 'https://github.com/anuragashok/wiremock-extension-record-delay?branch=main&edit_uri=/blob/main/'
          imports: [ /README.md ]
        
        # System
        - name: community
          import_url: 'https://github.com/wiremock/community?branch=main&edit_uri=/blob/main/'
          imports: [ contributing/* ]
        - name: dotgithub
          import_url: 'https://github.com/wiremock/.github?branch=main&edit_uri=/blob/main/'
          imports: [ CONTRIBUTING.md, SECURITY.md, CODE_OF_CONDUCT.md ]
        

nav:
  - Getting started:
      - Overview: overview
      - "Quick Start: API Mocking with Java and JUnit 4": quickstart/java-junit
      - Download and Installation: download-and-installation
      - WireMock Tutorials: getting-started
      - FAQ: faq

#    link: /docs/overview

  - WireMock Standalone:
    # link: /docs/standalone
      - Running in Docker: standalone/docker
      - Running as a Standalone Process: standalone/java-jar
      - Administration API: standalone/administration
  
  - Java Usage:
    # link: /docs/solutions/jvm/
      - JUnit 5+ Jupiter: junit-jupiter
      - JUnit 4 and Vintage: junit-extensions
      - Spring Boot: spring-boot
      - Plain Java: java-usage
      - Java configuration: configuration
      - Running without the HTTP Server: running-without-http-server
      
  - Stubbing & Verifying:
    #link: /docs/stubbing
      - Stubbing: stubbing
      - Request Matching: request-matching
      - Response Templating: response-templating
      - Simulating Faults: simulating-faults
      - Stateful Behaviour: stateful-behaviour
      - Proxying: proxying
      - Verifying: verifying
  
  - Templating:
    # link: /docs/mock-api-templates
      - WireMock API Templates Library: mock-api-templates
      - Using Mock API Templates: mock-api-templates/usage
  
  - Record & Playback:
    #link: /docs/record-playback/
      - Record and Playback: record-playback
  
  - Protocols:
      - Webhooks and Callbacks: webhooks-and-callbacks
      - Mocking gRPC services: grpc
      - WireMock and GraphQL: solutions/graphql
      - Serving HTTPs: https
  
  - Advanced use-cases:
      - Multi-domain Mocking: multi-domain-mocking
      - Deploying into a servlet container: advanced/deploy-to-servlet-container
      - "WireMock on Java 1.7": advanced/java7
  
  - Extensibility:
    # link: /docs/extending-wiremock/
      - Extending WireMock: extending-wiremock
      - Filtering and Modifying Requests: extensibility/filtering-requests
      - Transforming Responses: extensibility/transforming-responses
      - Custom Matching: extensibility/custom-matching
      - Listening for Serve Events: extensibility/listening-for-serve-events
      - Admin API Extensions: extensibility/extending-the-admin-api
      - Adding Template Helpers: extensibility/adding-template-helpers
      - Adding Template Model Data: extensibility/adding-template-model-data
      - Listening for Stub Changes: extensibility/listening-for-stub-changes
      - Listening for Settings Changes: extensibility/listening-for-settings-changes
      - Mappings Loader Extensions: extensibility/adding-mappings-loader
      - Stub Metadata: stub-metadata
  
  - Reference:
    # pages:
      - Admin API: standalone/admin-api-reference
      - WireMock API Templates Library: mock-api-templates

  - Extensions:
    - Features:
      - gRPC: grpc/README.md
      - GraphQL: graphql/README.md
      - Response Template Transformer: wiremock/_docs/response-templating.md
      - State: state/README.md
      - Webhooks: wiremock/_docs/webhooks-and-callbacks.md

      # Outside WireMock GitHub org
      - CORS protection: cors/README.md
      - JSON Web Tokens (JWT): jwt/README.md
      - JSON Body Transformer: 9cookies/json-body-transformer.md
      - Request Time Matcher: 9cookies/request-time-matcher.md
      
    - Operations Extensions:
      - Prometheus Metrics: prometheus/README.md

    - Developer Extensions:
      - Callback Simulator: 9cookies/callback-simulator.md
      - Keywords: 9cookies/keywords.md
      - Stub Mapping Tracker: stub-mapping-tracker/README.md
      - Record Delay Capture: record-delay/README.md

  - General:
    - Security: dotgithub/SECURITY.md

  - Contributing:
    - Contributor Guide: community/contributing/README.md 
    - Hacktoberfest 2023: dotgithub/CONTRIBUTING.md
    - Creating Extensions: wiremock/_docs/extending-wiremock.md
    - Code of Conduct: dotgithub/CODE_OF_CONDUCT.md

 # Markdown
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
