size: { width: 1200, height: 630 }
layers:
  - background:
      color: "#4051b5"
      typography:
        content: "{{ page.title }}" 
        overflow: shrink
        align: start
        color: white
        line:
          amount: 3
          height: 1.25
        font:
          family: DM
          style: Sans
  - size: { width: 280, height: 144 }
    offset: { x: 992, y: 64 }
    icon:
      color: white

